### ISSUE TITLE
Beginnings and ends of annotations aren't choosen correctly

### ISSUE THREAD

**Issue by Lifter-PL** [dimi2/DyAnnotationExtractor#3]
It seems that there is problem with correct selecting of beginnings and ends of annotations (text underlighting).
Please find attached example PDF (created with MS Word, annotation done with Adobe Acrobat Reader DC) and its result.
It seems that there is something wrong inside method convertAnnotation of class PdfAnnotationImporter.
PdfArray of Rectangle of annotation returned from PdfAnnotation object is equal to [189.668 720.475 463.451 732.205].
[test.pdf](https://github.com/dimi2/DyAnnotationExtractor/files/5631517/test.pdf)
[test.txt](https://github.com/dimi2/DyAnnotationExtractor/files/5631518/test.txt)

**Comment by dimi2** [comment]
Thank you for the bug report. 
The problem was that IText library does not cut text snippets crossing the extraction area boundaries. The problem was fixed in DyAnnotationExtractor version 1.2.
