### ISSUE TITLE
Mac OS workflow

### ISSUE THREAD

**Issue by Chris-mik** [dimi2/DyAnnotationExtractor#6]
That's a very powerful tool @dimi2!
Does the extractor work also for Mac OS?
Which are the steps that should be followed?

**Comment by dimi2** [comment]
Thank you.
The extractor was not tested on Mac Os, but it should work, since the software is Java-based. Just make sure you have installed Java version 8 or higher. Then follow the steps from the [readme](https://github.com/dimi2/DyAnnotationExtractor/blob/master/README.md).

**Comment by Chris-mik** [comment]
Since my coding background is limited, from the instructions I get that I should: i) instal java and ii) download and unzip the "DyAnnotationExtractor-1.3-dist.zip". Then, I am not sure which script I need to run so as to execute the conversion from a pdf to md in Terminal. 
Also, how the extractor handles two-column pdfs? Do the flow of annotations, from 1st column to 2nd column, is preserved in the extracted md output?
Thanks again!

**Comment by dimi2** [comment]
When you extract the zip archive, it will create directory DyAnnotationExtractor on your computer. Open terminal in that directory and execute script "DyAnnotationExtractor.sh", passing your pdf file as parameter. Like this:

    ./DyAnnotationExtractor.sh -input "MyAnnotatedFile.pdf"

If the execution does not start, complaining about 'Permission denied', you will have to make the script executable like this:

    chmod +x DyAnnotationExtractor.sh

The extractor does not keep the PDF text layout - it just extracts the annotations. So, if you have annotated texts in two table columns they will be extracted one after the other, or one under the other (depending on how the table was created). There will be no table in the output.

Greetings.
